"""add_billetes_loteria_table

Revision ID: 42ca2d39c5bd
Revises: 9a3f1d792cb8
Create Date: 2025-12-28 13:57:44.645115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42ca2d39c5bd'
down_revision = '9a3f1d792cb8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billetes_loteria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sorteo_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('disponible', 'tomado', name='estadobillete'), nullable=False),
    sa.Column('tomado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_tomado', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sorteo_id'], ['sorteos.id'], ),
    sa.ForeignKeyConstraint(['tomado_por'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sorteo_id', 'numero', name='unique_sorteo_numero')
    )
    op.create_index(op.f('ix_billetes_loteria_id'), 'billetes_loteria', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_billetes_loteria_id'), table_name='billetes_loteria')
    op.drop_table('billetes_loteria')
    # ### end Alembic commands ###
