"""change_numero_column_to_string

Revision ID: 709b18d37920
Revises: f1c5e342a833
Create Date: 2025-12-28 21:39:47.412023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '709b18d37920'
down_revision = 'f1c5e342a833'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('billetes_loteria', 'numero',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=3),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('billetes_loteria', 'numero',
               existing_type=sa.String(length=3),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
