"""add_sorteos_table

Revision ID: 9a3f1d792cb8
Revises: eb0eb0d98b72
Create Date: 2025-12-28 13:36:47.499703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a3f1d792cb8'
down_revision = 'eb0eb0d98b72'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sorteos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('natillera_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('loteria', 'rifa', name='tiposorteo'), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_sorteo', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.Enum('activo', 'finalizado', name='estadosorteo'), nullable=False),
    sa.Column('creador_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creador_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['natillera_id'], ['natilleras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sorteos_id'), 'sorteos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sorteos_id'), table_name='sorteos')
    op.drop_table('sorteos')
    # ### end Alembic commands ###
