"""change_numero_ganador_to_string

Revision ID: 9ca960d29f01
Revises: 709b18d37920
Create Date: 2025-12-29 19:04:50.967978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ca960d29f01'
down_revision = '709b18d37920'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sorteos', 'numero_ganador',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=3),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sorteos', 'numero_ganador',
               existing_type=sa.String(length=3),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
