"""update_enum_values

Revision ID: c0175bb9778b
Revises: c0fd07377cc0
Create Date: 2025-12-21 15:36:06.129588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0175bb9778b'
down_revision = 'c0fd07377cc0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
