"""fix_pagos_prestamo_table

Revision ID: c0fd07377cc0
Revises: 12ec9791492c
Create Date: 2025-12-21 15:34:53.345525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0fd07377cc0'
down_revision = '12ec9791492c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transacciones_aporte_id_unique', table_name='transacciones', postgresql_where='(aporte_id IS NOT NULL)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_transacciones_aporte_id_unique', 'transacciones', ['aporte_id'], unique=True, postgresql_where='(aporte_id IS NOT NULL)')
    # ### end Alembic commands ###
