"""add archivos_adjuntos table

Revision ID: eb0eb0d98b72
Revises: fa6e84cedf4e
Create Date: 2025-12-25 11:24:47.006202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb0eb0d98b72'
down_revision = 'fa6e84cedf4e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archivos_adjuntos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_archivo', sa.String(), nullable=False),
    sa.Column('ruta_archivo', sa.String(), nullable=False),
    sa.Column('tipo_archivo', sa.String(), nullable=False),
    sa.Column('tamano', sa.Integer(), nullable=False),
    sa.Column('fecha_subida', sa.DateTime(), nullable=False),
    sa.Column('id_aporte', sa.Integer(), nullable=True),
    sa.Column('id_pago_prestamo', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_aporte'], ['aportes.id'], ),
    sa.ForeignKeyConstraint(['id_pago_prestamo'], ['pagos_prestamo.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_archivos_adjuntos_id'), 'archivos_adjuntos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_archivos_adjuntos_id'), table_name='archivos_adjuntos')
    op.drop_table('archivos_adjuntos')
    # ### end Alembic commands ###
