"""add_pagado_to_billetes_and_numero_ganador_to_sorteos

Revision ID: f1c5e342a833
Revises: 42ca2d39c5bd
Create Date: 2025-12-28 14:15:50.776719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1c5e342a833'
down_revision = '42ca2d39c5bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Agregar columna pagado como nullable inicialmente
    op.add_column('billetes_loteria', sa.Column('pagado', sa.Boolean(), nullable=True))
    # Actualizar valores existentes a False
    op.execute("UPDATE billetes_loteria SET pagado = false WHERE pagado IS NULL")
    # Hacer la columna NOT NULL
    op.alter_column('billetes_loteria', 'pagado', nullable=False)
    op.add_column('sorteos', sa.Column('numero_ganador', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sorteos', 'numero_ganador')
    op.drop_column('billetes_loteria', 'pagado')
    # ### end Alembic commands ###
